### ISSUE TITLE
PartiallySignedTransaction Finalization is throwing an exception for a valid control block

### ISSUE THREAD

**Issue by Ashleyhen** [rust-bitcoin/rust-bitcoin#1195]
Please copy and run the code below to see the exception

Following the example of [tapscript-example-with-tap](https://github.com/bitcoin-core/btcdeb/blob/master/doc/tapscript-example-with-tap.md) using the same data, I noticed that the tap tool was able to finalize and sign for a transaction on the regtest network but when you try to sign for the same data using bitcoin rust you get an exception. 

In the tapscript example, they use a lot of environment variables so I create this bash script to make it easier to work with, 

<details>
<summary>Bash helper</summary>

```bash
privkey="1229101a0fcf2104e8808dab35661134aa5903867d44deb73ce1c7e4eb925be8"
pubkey="f30544d6009c8d8d94f5d030b2e844b1a3ca036255161c479db1cca5b374dd1c"
script_alice="'[144 OP_CHECKSEQUENCEVERIFY OP_DROP 9997a497d964fc1a62885b05a51166a65a90df00492c8d7cf61d6accf54803be OP_CHECKSIG]'"
script_bob="'[OP_SHA256 6c60f404f8167a38fc70eaf8aa17ac351023bef86bcb9d1086a19afe95bd5333 OP_EQUALVERIFY 4edfcf9dfe6c0b5c83d1ab3f78d1b39a46ebac6798e08e19761f5ed89ec83c10 OP_CHECKSIG]'" 
vout=0 # CONFIRM THIS OR THINGS WILL FAIL
txin="020000000001010aa633878f200c80fc8ec88f13f746e5870be7373ad5d78d22e14a402d6c6fc20000000000feffffff02a086010000000000225120a5ba0871796eb49fb4caa6bf78e675b9455e2d66e751676420f8381d5dda8951c759f405000000001600147bf84e78c81b9fed7a47b9251d95b13d6ebac14102473044022017de23798d7a01946744421fbb79a48556da809a9ffdb729f6e5983051480991022052460a5082749422804ad2a25e6f8335d5cf31f69799cece4a1ccc0256d5010701210257e0052b0ec6736ee13392940b7932571ce91659f71e899210b8daaf6f17027500000000"
tx="020000000171f2f89c07c3b58c7b0cf3654ba049d28bbcc76b7298f41c17e7b1a3149040ec0000000000ffffffff01905f010000000000160014ceb2d28afdcad1ae0fc2cf81cb929ba29e83468200000000"
echo tap $pubkey 2 $script_alice $script_bob
echo 
echo tap --tx=$tx --txin=$txin $pubkey 2 $script_alice $script_bob 
echo 
echo tap --privkey=$privkey --tx=$tx --txin=$txin $pubkey 2 $script_alice $script_bob
echo
echo tap --tx=$tx --txin=$txin $pubkey 2 $script_alice $script_bob 1
echo
echo tap -k81b637d8fcd2c6da6359e6963113a1170de795e4b725b84d1e0b4cfd9ec58ce9 --tx=$tx --txin=$txin $pubkey 2 $script_alice $script_bob 1 107661134f21fc7c02223d50ab9eb3600bc3ffc3712423a1e47bb1f9a9dbf55f
# tap $pubkey 2 $script_alice $script_bob

```

</details>

<details>
  <summary>implentation in rust</summary>
  
  ### Rust Implentation
  ```rust
use std::collections::BTreeMap;
use std::{ str::FromStr};

use bitcoin::psbt::{Input, PartiallySignedTransaction, TapTree};
use bitcoin::secp256k1::{Message, Parity};
use bitcoin::util::taproot::LeafVersion::TapScript;
use bitcoin::util::taproot::{ControlBlock, LeafVersion};
use bitcoin::{
    blockdata::{opcodes::all, script::Builder},
    hashes::{hex::FromHex, sha256, Hash},
    psbt::serialize::Deserialize,
    schnorr::{TapTweak},
    secp256k1::{Secp256k1, SecretKey},
    util::{
        sighash::{Prevouts, SighashCache},
        taproot::{
             TapBranchHash, TapLeafHash, TaprootBuilder,
            TaprootMerkleBranch, 
        },
    },
    Address, KeyPair, SchnorrSighashType, Script, Transaction,
     Witness,
};
use bitcoin::{ SchnorrSig};
use bitcoin_hashes::hex::ToHex;
use miniscript::psbt::{PsbtExt};

pub fn Test() {

    use bitcoin_hashes::Hash;
    let secp = Secp256k1::new();
    let alice_secret =
        SecretKey::from_str("2bd806c97f0e00af1a1fc3328fa763a9269723c8db8fac4f93af71db186d6e90")
            .unwrap();
    let bob_secret =
        SecretKey::from_str("81b637d8fcd2c6da6359e6963113a1170de795e4b725b84d1e0b4cfd9ec58ce9")
            .unwrap();
    let internal_secret =
        SecretKey::from_str("1229101a0fcf2104e8808dab35661134aa5903867d44deb73ce1c7e4eb925be8")
            .unwrap();

    let alice = KeyPair::from_secret_key(&secp, alice_secret);
    let bob = KeyPair::from_secret_key(&secp, bob_secret);
    let internal = KeyPair::from_secret_key(&secp, internal_secret);
    let preimage = Vec::from_hex("107661134f21fc7c02223d50ab9eb3600bc3ffc3712423a1e47bb1f9a9dbf55f").unwrap();

    let preimage_hash = bitcoin_hashes::sha256::Hash::hash(&preimage);

    println!("alice public key {}", alice.public_key());
    println!("bob public key {}", bob.public_key());
    println!("internal public key {}", internal.public_key());

    println!("preimage {}", preimage_hash.to_string());

    let alice_script = Script::from_hex(
        "029000b275209997a497d964fc1a62885b05a51166a65a90df00492c8d7cf61d6accf54803beac",
    )
    .unwrap();

    let bob_script = Builder::new()
        .push_opcode(all::OP_SHA256)
        .push_slice(&preimage_hash)
        .push_opcode(all::OP_EQUALVERIFY)
        .push_x_only_key(&bob.public_key())
        .push_opcode(all::OP_CHECKSIG)
        .into_script();

    let alice_leaf = TapLeafHash::from_script(&alice_script, TapScript);
    let bob_leaf = TapLeafHash::from_script(&bob_script, TapScript);

    let alice_branch = TapBranchHash::from_inner(alice_leaf.into_inner());
    let bob_branch = TapBranchHash::from_inner(bob_leaf.into_inner());

    let branch = TapBranchHash::from_node_hashes(
        sha256::Hash::from_inner(alice_branch.into_inner()),
        sha256::Hash::from_inner(bob_branch.into_inner()),
    );

    let builder =
        TaprootBuilder::with_huffman_tree(vec![(1, bob_script.clone()), (1, alice_script.clone())])
            .unwrap();

    let tap_tree = TapTree::from_builder(builder).unwrap();

    let tap_info = tap_tree
        .into_builder()
        .finalize(&secp, internal.public_key())
        .unwrap();

    let tweak_key_pair = internal.tap_tweak(&secp, Some(branch)).into_inner();
    

    let address = Address::p2tr(
        &secp,
        internal.public_key(),
        Some(branch),
        bitcoin::Network::Regtest,
    );

    println!("tweaked address {} ",address.to_string());
    let tx = unsigned_tx();

    let sighash_sig = SighashCache::new(&mut tx.clone())
        .taproot_script_spend_signature_hash(
            0,
            &Prevouts::All(&vec![tx_input().output[0].clone()]),
            bob_leaf,
            SchnorrSighashType::Default,
        )
        .unwrap();

    let prev_outs = vec![tx_input().output[0].clone()];
    let key_sig = SighashCache::new(&mut tx.clone())
        .taproot_key_spend_signature_hash(
            0,
            &Prevouts::All(&prev_outs),
            SchnorrSighashType::Default,
        )
        .unwrap();

    println!("key signing sighash {} ", key_sig);

    println!("script sighash {} ", sighash_sig);

    let sig = secp.sign_schnorr(
        &Message::from_slice(&sighash_sig).unwrap(),
        &bob.tap_tweak(&secp, Some(branch)).into_inner(),
    );

    let actual_control = ControlBlock {
        leaf_version: LeafVersion::TapScript,
        output_key_parity: Parity::Odd,
        internal_key: internal.public_key(),
        merkle_branch: TaprootMerkleBranch::from_slice(&alice_leaf).unwrap(),
    };

    let res =
        actual_control.verify_taproot_commitment(&secp, tweak_key_pair.public_key(), &bob_script);

    println!("is taproot comitented? {} ",res);

    println!(" control block {} ", actual_control.serialize().to_hex());

    let mut input = Input::default();

    let mut b_tree_map = BTreeMap::<ControlBlock, (Script, LeafVersion)>::default();
    b_tree_map.insert(
        actual_control.clone(),
        (bob_script.clone(), LeafVersion::TapScript),
    );

    input.tap_scripts = b_tree_map;
    input.tap_internal_key = Some(internal.public_key());

    input.witness_utxo = Some(tx_input().output[0].clone());
    input.tap_merkle_root = Some(branch);

    let pst = PartiallySignedTransaction {
        unsigned_tx: unsigned_tx(),
        version: 2,
        xpub: BTreeMap::default(),
        proprietary: BTreeMap::default(),
        unknown: BTreeMap::default(),
        inputs: vec![input],
        outputs: vec![],
    };

    let schnorr_sig = SchnorrSig {
        sig,
        hash_ty: SchnorrSighashType::Default,
    };

    // this part fails
    pst.finalize(&secp).unwrap();

    // sig
    println!("signature {}", sig);
    println!("Input preimage {}", preimage.to_hex());
    println!("script {}", bob_script.to_hex());
    println!("control block {:#?}", actual_control.serialize().to_hex());
    let wit = Witness::from_vec(vec![
        schnorr_sig.to_vec(),
        preimage,
        bob_script.to_bytes(),
        actual_control.serialize(),
    ]);
    dbg!(wit);
}

pub fn unsigned_tx() -> Transaction {
    return Transaction::deserialize(&Vec::from_hex("020000000171f2f89c07c3b58c7b0cf3654ba049d28bbcc76b7298f41c17e7b1a3149040ec0000000000ffffffff01905f010000000000160014ceb2d28afdcad1ae0fc2cf81cb929ba29e83468200000000").unwrap()).unwrap();
}

pub fn tx_input() -> Transaction {
    return Transaction::deserialize(&Vec::from_hex("020000000001010aa633878f200c80fc8ec88f13f746e5870be7373ad5d78d22e14a402d6c6fc20000000000feffffff02a086010000000000225120a5ba0871796eb49fb4caa6bf78e675b9455e2d66e751676420f8381d5dda8951c759f405000000001600147bf84e78c81b9fed7a47b9251d95b13d6ebac14102473044022017de23798d7a01946744421fbb79a48556da809a9ffdb729f6e5983051480991022052460a5082749422804ad2a25e6f8335d5cf31f69799cece4a1ccc0256d5010701210257e0052b0ec6736ee13392940b7932571ce91659f71e899210b8daaf6f17027500000000").unwrap()).unwrap();
}

pub fn signed_tx() -> Transaction {
    return Transaction::deserialize(&Vec::from_hex("0200000000010171f2f89c07c3b58c7b0cf3654ba049d28bbcc76b7298f41c17e7b1a3149040ec0000000000ffffffff01905f010000000000160014ceb2d28afdcad1ae0fc2cf81cb929ba29e834682044054d5ee309be92f531d62449d8ef82b216f1e5b6229aaef918a78c26ce6dd66d57c523202b4650302667723f63dd5a87b2370ada51e08de0eccb27a80450ff9bf20107661134f21fc7c02223d50ab9eb3600bc3ffc3712423a1e47bb1f9a9dbf55f45a8206c60f404f8167a38fc70eaf8aa17ac351023bef86bcb9d1086a19afe95bd533388204edfcf9dfe6c0b5c83d1ab3f78d1b39a46ebac6798e08e19761f5ed89ec83c10ac41c1f30544d6009c8d8d94f5d030b2e844b1a3ca036255161c479db1cca5b374dd1cc81451874bd9ebd4b6fd4bba1f84cdfb533c532365d22a0a702205ff658b17c900000000").unwrap()).unwrap();
}

  ```
</details>

exception message
```
control block c1f30544d6009c8d8d94f5d030b2e844b1a3ca036255161c479db1cca5b374dd1cc81451874bd9ebd4b6fd4bba1f84cdfb533c532365d22a0a702205ff658b17c9 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: (PartiallySignedTransaction { unsigned_tx: Transaction { version: 2, lock_time: 0, input: [TxIn { previous_output: OutPoint { txid: ec409014a3b1e7171cf498726bc7bc8bd249a04b65f30c7b8cb5c3079cf8f271, vout: 0 }, script_sig: Script(), sequence: 4294967295, witness: Witness { content: [], witness_elements: 0, last: 0, second_to_last: 0 } }], output: [TxOut { value: 90000, script_pubkey: Script(OP_0 OP_PUSHBYTES_20 ceb2d28afdcad1ae0fc2cf81cb929ba29e834682) }] }, version: 2, xpub: {}, proprietary: {}, unknown: {}, inputs: [Input { non_witness_utxo: None, witness_utxo: Some(TxOut { value: 100000, script_pubkey: Script(OP_PUSHNUM_1 OP_PUSHBYTES_32 a5ba0871796eb49fb4caa6bf78e675b9455e2d66e751676420f8381d5dda8951) }), partial_sigs: {}, sighash_type: None, redeem_script: None, witness_script: None, bip32_derivation: {}, final_script_sig: None, final_script_witness: None, ripemd160_preimages: {}, sha256_preimages: {}, hash160_preimages: {}, hash256_preimages: {}, tap_key_sig: None, tap_script_sigs: {}, tap_scripts: {ControlBlock { leaf_version: TapScript, output_key_parity: Odd, internal_key: XOnlyPublicKey(1cdd74b3a5ccb19d471c16556203caa3b144e8b230d0f5948d8d9c00d64405f3060dafe3d713cd37d877feee9add5f39874a214b19278d25e9534cd20014db1c), merkle_branch: TaprootMerkleBranch([c81451874bd9ebd4b6fd4bba1f84cdfb533c532365d22a0a702205ff658b17c9]) }: (Script(OP_SHA256 OP_PUSHBYTES_32 6c60f404f8167a38fc70eaf8aa17ac351023bef86bcb9d1086a19afe95bd5333 OP_EQUALVERIFY OP_PUSHBYTES_32 4edfcf9dfe6c0b5c83d1ab3f78d1b39a46ebac6798e08e19761f5ed89ec83c10 OP_CHECKSIG), TapScript)}, tap_key_origins: {}, tap_internal_key: Some(XOnlyPublicKey(1cdd74b3a5ccb19d471c16556203caa3b144e8b230d0f5948d8d9c00d64405f3060dafe3d713cd37d877feee9add5f39874a214b19278d25e9534cd20014db1c)), tap_merkle_root: Some(41646f8c1fe2a96ddad7f5471bc4fee7da98794ef8c45a4f4fc6a559d60c9f6b), proprietary: {}, unknown: {} }], outputs: [] }, [InputError(CouldNotSatisfyTr, 0)])', src/wallet_test/tapscript_example_with_tap.rs:174:25
stack backtrace:
   0:     0x5647a83144ec - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5647a83144ec - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5647a83144ec - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
```

The exact line where the issue occurs seems to be related to [this line](https://github.com/rust-bitcoin/rust-miniscript/blob/9fd9aa46a8df3a7463456e947c94490f4887e74a/src/miniscript/decode.rs#L360)

**Comment by JeremyRubin** [comment]
This looks like expected behavior (haven't looked too deeply).

You're unwrapping an atempted finalization, and the attempt fails.

The control block may be valid, but rust-bitcoin does not know how to assemble the witness for a custom script.

**Comment by Ashleyhen** [comment]
If I build the transaction with the witness manually I can replace the function "unsigned_tx()" with "signed_tx()" function which contains the signed tx from [tapscript-example-with-tap](https://github.com/bitcoin-core/btcdeb/blob/master/doc/tapscript-example-with-tap.md) which still fails when I go to finalize the pariallysignedtransaction

**Comment by Ashleyhen** [comment]
If not would you please be able to provide some insight on what modifications must be done in order to derive a valid spend script path?

**Comment by JeremyRubin** [comment]
Well it isn't magic, it has to know how to satisfy it using the templates it can fill in.

Peep the error you're getting from finalize: `[InputError(CouldNotSatisfyTr, 0)]`

It is failing to satisfy input 0, most likely in the call to construct_tap_witness.

**Comment by sanket1729** [comment]
@Ashleyhen, the script you are trying to finalize is not miniscript. The finalizer of rust-miniscript cannot assemble a witness for it. You would need to explicitly construct the witness for non-miniscripts. 

You can obtain the control block/taproot info via https://docs.rs/bitcoin/0.28.0/bitcoin/util/taproot/struct.TaprootSpendInfo.html to get the control block.

**Comment by sanket1729** [comment]
@Ashleyhen , you can see the updated example here. https://github.com/sanket1729/rust-miniscript/blob/tap_example/examples/tap_script_spend.rs

I have also updated the example with other APIs that you can use. Hopefully, the new code offers a better high-level API. 

Because the used script is not a miniscript, we cannot use the finalization:( . We have to add the final_witness manually. 

Lastly, thanks for submitting your code. It is incredibly valuable to see how people are using the code so that we can learn to document our APIs/add examples to aid.

**Comment by Ashleyhen** [comment]
Hey sorry for the late reply I've been trying to test this solution for the past few days before I close this ticket. But unfortunately, I've kept running into issues.  https://docs.rs/bitcoincore-rpc/latest/bitcoincore_rpc/ doesn't support taproot. Electrum doesn't support Regnet JSON RPC calls and trying to format a raw RPC call hasn't been very easy. Alternatively I suppose I could try this on Test net but that doesn't seem as Ideal as being able to test on regtest. Is there any practical way you know of to test this on regtest.

**Comment by Ashleyhen** [comment]
Since the main point of of this issue has been addressed I'm going to close this
