### ISSUE TITLE
MemorySanitizer is erroring

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2579]
We are hitting an intermittent MemorySanitizer error, locally on `master` I can repro it every time but some CI runs are hitting it and some not:

- #2541 hit it.
- I hit it yesterday and re-ran to get past CI.
- #2576 and #2577 did not hit it.

### Reproducer

Using the following diff:
```diff
diff --git a/contrib/run_task.sh b/contrib/run_task.sh
index f7aa21ac..e4213654 100755
--- a/contrib/run_task.sh
+++ b/contrib/run_task.sh
@@ -207,12 +207,12 @@ do_wasm() {
 }
 
 do_asan() {
-    cargo clean
-    CC='clang -fsanitize=address -fno-omit-frame-pointer'                                        \
-      RUSTFLAGS='-Zsanitizer=address -Clinker=clang -Cforce-frame-pointers=yes'                    \
-      ASAN_OPTIONS='detect_leaks=1 detect_invalid_pointer_pairs=1 detect_stack_use_after_return=1' \
-      cargo test --lib --no-default-features --features="$ASAN_FEATURES" -Zbuild-std --target x86_64-unknown-linux-gnu
-    cargo clean
+    # cargo clean
+    # CC='clang -fsanitize=address -fno-omit-frame-pointer'                                        \
+    #   RUSTFLAGS='-Zsanitizer=address -Clinker=clang -Cforce-frame-pointers=yes'                    \
+    #   ASAN_OPTIONS='detect_leaks=1 detect_invalid_pointer_pairs=1 detect_stack_use_after_return=1' \
+    #   cargo test --lib --no-default-features --features="$ASAN_FEATURES" -Zbuild-std --target x86_64-unknown-linux-gnu
+    # cargo clean
     CC='clang -fsanitize=memory -fno-omit-frame-pointer'                                         \
       RUSTFLAGS='-Zsanitizer=memory -Zsanitizer-memory-track-origins -Cforce-frame-pointers=yes'   \
       cargo test --lib --no-default-features --features="$ASAN_FEATURES" -Zbuild-std --target x86_64-unknown-linux-gnu
```
 
And running `RUSTUP_TOOLCHAIN=nightly contrib/run_task.sh bitcoin asan`

I get:
```
==697612==WARNING: MemorySanitizer: use-of-uninitialized-value
test address::tests::p2tr_from_untweaked ... ok
    #0 0x55649426d38f  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x180038f) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #1 0x556493cb9c42  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x124cc42) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #2 0x5564934e33e7  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0xa763e7) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #3 0x5564934e420f  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0xa7720f) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #4 0x556493156353  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x6e9353) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #5 0x556493577634  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0xb0a634) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #6 0x55649322ec9a  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x7c1c9a) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #7 0x556493f59e9f  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x14ece9f) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #8 0x556493dc6175  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x1359175) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #9 0x5564940086a1  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x159b6a1) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #10 0x556493dc8a8e  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x135ba8e) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #11 0x556493fa7832  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x153a832) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #12 0x556493dd96d3  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x136c6d3) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #13 0x556493e198bb  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x13ac8bb) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #14 0x556493dd90d9  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x136c0d9) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #15 0x556493e41a44  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x13d4a44) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #16 0x556493dc6e2b  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x1359e2b) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #17 0x556493dc4f5e  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x1357f5e) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #18 0x556493dc5f78  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x1358f78) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #19 0x556493e55fb5  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x13e8fb5) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #20 0x556493d9384d  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x132684d) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #21 0x556493fa7651  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x153a651) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #22 0x556493dd9d9e  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x136cd9e) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #23 0x556493e198bb  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x13ac8bb) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #24 0x556493dd76e5  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x136a6e5) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #25 0x556493e4185a  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x13d485a) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #26 0x556493d92fc7  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x1325fc7) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #27 0x556493f59517  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x14ec517) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #28 0x556494727517  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x1cba517) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #29 0x556494727899  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x1cba899) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #30 0x556494a97359  (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x202a359) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d)
    #31 0x7ffb1e00dac2  (/lib/x86_64-linux-gnu/libc.so.6+0x94ac2) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)
    #32 0x7ffb1e09f84f  (/lib/x86_64-linux-gnu/libc.so.6+0x12684f) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce+0x180038f) (BuildId: fc99afed7ecc821e8a43cb28af7b8d159f12f16d) 
  ORIGIN: invalid (0). Might be a bug in MemorySanitizer origin tracking.
    This could still be a bug in your code, too!
Exiting
error: test failed, to rerun pass `--lib`

Caused by:
  process didn't exit successfully: `/home/tobin/.cache/cargo/x86_64-unknown-linux-gnu/debug/deps/bitcoin-d9afebffc8aaf5ce` (exit status: 1)
note: test exited abnormally; to see the full output pass --nocapture to the harness.
```

**Comment by tcharding** [comment]
I'm debugging now, posted the issue for any tips or pointers. I've never debugged memory sanitizer bugs before.

**Comment by tcharding** [comment]
Update: Putting `llvm-symbolizer` in my path gives better output (I just symlinked to `llvm-symbolizer-15`)
```
==698820==WARNING: MemorySanitizer: use-of-uninitialized-value
test address::tests::p2tr_from_untweaked ... ok
test address::tests::test_address_type ... ok
    #0 0x5600c8efa38f in rustsecp256k1_v0_9_1_ec_pubkey_parse /home/tobin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/secp256k1-sys-0.9.1/depend/secp256k1/src/secp256k1.c:230:5
    #1 0x5600c8946c42 in secp256k1::key::PublicKey::from_slice::hb885713697150fff /home/tobin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/secp256k1-0.28.0/src/key.rs:474:16
    #2 0x5600c81703e7 in bitcoin::crypto::key::PublicKey::from_slice::h87a6caf85891459b /home/tobin/build/github.com/tcharding/rust-bitcoin/master/bitcoin/src/crypto/key.rs:191:43
    #3 0x5600c817120f in _$LT$bitcoin..crypto..key..PublicKey$u20$as$u20$core..str..traits..FromStr$GT$::from_str::h123c3ec7867167a5 /home/tobin/build/github.com/tcharding/rust-bitcoin/master/bitcoin/src/crypto/key.rs:244:20
    #4 0x5600c7de3353 in bitcoin::address::tests::test_is_related_to_pubkey_p2pkh::h2525cdfd9d021db3 /home/tobin/build/github.com/tcharding/rust-bitcoin/master/bitcoin/src/address/mod.rs:1149:22
    #5 0x5600c8204634 in bitcoin::address::tests::test_is_related_to_pubkey_p2pkh::_$u7b$$u7b$closure$u7d$$u7d$::h1990d2931b56049f /home/tobin/build/github.com/tcharding/rust-bitcoin/master/bitcoin/src/address/mod.rs:1141:41
    #6 0x5600c7ebbc9a in core::ops::function::FnOnce::call_once::h749581b42efb11af /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
    #7 0x5600c8be6e9f in core::ops::function::FnOnce::call_once::h3b1350bf8f2993e6 /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
    #8 0x5600c8a53175 in test::__rust_begin_short_backtrace::h5a4c185ddb72f9f2 /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:621:18
    #9 0x5600c8c956a1 in test::types::RunnableTest::run::h97f046c886ad5cfe /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/types.rs:146:40
    #10 0x5600c8a55a8e in test::run_test_in_process::_$u7b$$u7b$closure$u7d$$u7d$::h2bcd0c73805bbade /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:644:60
    #11 0x5600c8c34832 in _$LT$core..panic..unwind_safe..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::hd049b77e2300265b /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
    #12 0x5600c8a666d3 in std::panicking::try::do_call::h437257e26044ba87 /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40
    #13 0x5600c8aa68bb in __rust_try test.9476458f7c7bd72-cgu.03
    #14 0x5600c8a660d9 in std::panicking::try::hc5a4eeed64dedd8c /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19
    #15 0x5600c8acea44 in std::panic::catch_unwind::he493ee22209f3a62 /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:142:14
    #16 0x5600c8a53e2b in test::run_test_in_process::h07cde775b511c899 /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:644:27
    #17 0x5600c8a51f5e in test::run_test::_$u7b$$u7b$closure$u7d$$u7d$::h1ba2d8dfb9680f60 /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:567:43
    #18 0x5600c8a52f78 in test::run_test::_$u7b$$u7b$closure$u7d$$u7d$::heba1fea5bb4f7c0e /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:595:41
    #19 0x5600c8ae2fb5 in std::sys_common::backtrace::__rust_begin_short_backtrace::h5d3c0ba8dce85d24 /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18
    #20 0x5600c8a2084d in std::thread::Builder::spawn_unchecked_::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h623356342d140752 /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:528:17
    #21 0x5600c8c34651 in _$LT$core..panic..unwind_safe..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h3dabe57cdb7ca925 /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
    #22 0x5600c8a66d9e in std::panicking::try::do_call::hddb94246df1b04e2 /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40
    #23 0x5600c8aa68bb in __rust_try test.9476458f7c7bd72-cgu.03
    #24 0x5600c8a646e5 in std::panicking::try::h0147aba6bdea2ccb /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19
    #25 0x5600c8ace85a in std::panic::catch_unwind::h4932be1108fe4602 /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:142:14
    #26 0x5600c8a1ffc7 in std::thread::Builder::spawn_unchecked_::_$u7b$$u7b$closure$u7d$$u7d$::hb6156eb7c0d33a87 /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:527:30
    #27 0x5600c8be6517 in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::hfd58c5090ae2275c /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
    #28 0x5600c93b4517 in _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::h13c5bc0722710c0d /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2016:9
    #29 0x5600c93b4899 in _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::h207187859fc1de0b /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2016:9
    #30 0x5600c9724359 in std::sys::pal::unix::thread::Thread::new::thread_start::h4f4246934725cde6 /home/tobin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/pal/unix/thread.rs:108:17
    #31 0x7fcc946c5ac2 in start_thread nptl/pthread_create.c:442:8
    #32 0x7fcc9475784f  misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/tobin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/secp256k1-sys-0.9.1/depend/secp256k1/src/secp256k1.c:230:5 in rustsecp256k1_v0_9_1_ec_pubkey_parse
  ORIGIN: invalid (0). Might be a bug in MemorySanitizer origin tracking.
    This could still be a bug in your code, too!
Exiting
```

**Comment by tcharding** [comment]
Oh sweet, I think this will be fixed by #2576!

**Comment by tcharding** [comment]
Interesting, it seems to come from the new code we introduced in #2473 and is __not__ fixed by #2576. I'm unsure if its the patch to `rust-bitcoin` that is the problem or some of the other work we did in `hex-conservative`?

This is the start of the call chain that is triggering the issue:

```rust
impl FromStr for PublicKey {
    type Err = ParsePublicKeyError;
    fn from_str(s: &str) -> Result<PublicKey, ParsePublicKeyError> {
        use HexToArrayError::*;

        match s.len() {
            66 => {
                let bytes = <[u8; 33]>::from_hex(s).map_err(|e| match e {
                    InvalidChar(e) => ParsePublicKeyError::InvalidChar(e.invalid_char()),
                    InvalidLength(_) => unreachable!("length checked already")
                })?;
                Ok(PublicKey::from_slice(&bytes)?)
            },
            130 => {
                let bytes = <[u8; 65]>::from_hex(s).map_err(|e| match e {
                    InvalidChar(e) => ParsePublicKeyError::InvalidChar(e.invalid_char()),
                    InvalidLength(_) => unreachable!("length checked already")
                })?;
                Ok(PublicKey::from_slice(&bytes)?)
            }
            len => Err(ParsePublicKeyError::InvalidHexLength(len)),
        }
    }
}
```

**Comment by tcharding** [comment]
I was unable to reslove this today, here are my findings:

- The call chain is `bitcoin::PublicKey::from_slice` -> `secp256k1::PublicKey::from_slice` -> `ffi::secp256k1_ec_pubkey_parse`
- `secp256k1_ec_pubkey_parse` uses `data.as_c_ptr()` to get a pointer to the data array (`unsigned char *`)
- Accessing the first element of the data array triggers the MSAN error
- Right before the FFI call the data slice is non-empty

```rust
            // Sanity, just ensure we can access the first element here.
            if data[0] == 0xff {
                panic!("first element of data is 0xff")
            }
            let pointer = data.as_c_ptr();
            if pointer.is_null() {
                panic!("pointer is null");
            }
```

No further ideas ATM.

**Comment by tcharding** [comment]
@apoelstra if you get a chance can you give this ten minutes and give some pointers on which direction to look please?

**Comment by tcharding** [comment]
ooo, it might not be the `pub` arg at all - debugging now. Posting incase you get here at the same time.

**Comment by tcharding** [comment]
Its the `inputlen` arg that is triggering the error! (a Rust `usize` passed across ffi as a `size_t` - this is definitely a bug in MSAN.

**Comment by tcharding** [comment]
MSAN also errors for `size_t` arguments, even when I replace the `usize` on the otherside of the FFI boundry with a local variable.

Change `key.rs` lines 556 - 567 to be (ie, line 560 is the FFI function call)
```rust
        let mut ret = [0_u8; 66];
        let mut ret_len = 66;

        let res = unsafe {
            ffi::secp256k1_ec_pubkey_serialize(
                ffi::secp256k1_context_no_precomp,
                ret.as_mut_c_ptr(),
                &mut ret_len,
                self.as_c_ptr(),
                flag,
            )
        };
```
Still gives
```
==892789==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5591f749a2b7 in rustsecp256k1_v0_9_2_ec_pubkey_serialize /home/tobin/build/github.com/tcharding/rust-secp256k1/master/secp256k1-sys/depend/secp256k1/src/secp256k1.c:279:5
    #1 0x5591f6881b09 in secp256k1::key::PublicKey::serialize_internal::hd1155a157cd04844 /home/tobin/build/github.com/tcharding/rust-secp256k1/master/src/key.rs:560:13
    #2 0x5591f6881b09 in secp256k1::key::PublicKey::serialize_uncompressed::hc4d3025786944379 /home/tobin/build/github.com/tcharding/rust-secp256k1/master/src/key.rs:550:9
```

**Comment by apoelstra** [comment]
I cannot repro. When I try to run the test I get

```
FATAL: Code 0x60c539d809b0 is out of application range. Non-PIE build?
FATAL: MemorySanitizer can not mmap the shadow memory.
FATAL: Make sure to compile with -fPIE and to link with -pie.
FATAL: Disabling ASLR is known to cause this error.
FATAL: If running under GDB, try 'set disable-randomization off'.
```

**Comment by apoelstra** [comment]
Running in gdb everything seems fine. If I run in valgrind it says `==1124717== Warning: set address range perms: large range [0x10000000000, 0x100000000000) (defined)` then apperas to lock up.

**Comment by apoelstra** [comment]
I wonder if we are hitting https://github.com/bitcoin-core/secp256k1/issues/1506

**Comment by real-or-random** [comment]
> I wonder if we are hitting [bitcoin-core/secp256k1#1506](https://github.com/bitcoin-core/secp256k1/issues/1506)

Yes, this really looks like https://github.com/google/sanitizers/issues/1614

**Comment by apoelstra** [comment]
In the linked libsecp issue fanquake says that the upstream problem should be fixed (in github actions), so maybe we can re-enable msan.

But can maybe wait til after the release because futzing with CI is time-consuming and annoying.

**Comment by Kixunil** [comment]
Can we enable this?

**Comment by apoelstra** [comment]
Yep, I'm sure we can now.

I wonder if we'd get it for free if we switched to the maintainer-tools CI scripts ... if not, we should fix that in rust-bitcoin-maintainer-tools.

Meanwhile I'd be happy to take a PR that just reenables it with the current CI setup.
