### ISSUE TITLE
Compiling invalid policy "or(pk())" causes "index out of bounds: the len is 1 but the index is 1"

### ISSUE THREAD

**Issue by practicalswift** [rust-bitcoin/rust-bitcoin#324]
Compiling invalid policy `or(pk())` causes `index out of bounds: the len is 1 but the index is 1`:

```
use miniscript::{policy, DummyKey};
use std::str::FromStr;

type DummyPolicy = policy::Concrete<DummyKey>;

fn main() {
    let policy_string = "or(pk())";
    if let Ok(policy) = DummyPolicy::from_str(&policy_string) {
        if let Ok(_) = policy.compile() {}
    }
}
```

```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/9af17757be1cc3f672928ecf06c40a662c5ec26d/src/libcore/slice/mod.rs:2715:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
  11: <usize as core::slice::SliceIndex<[T]>>::index
             at /rustc/9af17757be1cc3f672928ecf06c40a662c5ec26d/src/libcore/slice/mod.rs:2715
  12: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/9af17757be1cc3f672928ecf06c40a662c5ec26d/src/libcore/slice/mod.rs:2566
  13: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/9af17757be1cc3f672928ecf06c40a662c5ec26d/src/liballoc/vec.rs:1792
  14: miniscript::policy::compiler::best_compilations
             at DIR/.cargo/git/checkouts/rust-miniscript-1175aea50517de2b/8ad6fea/src/policy/compiler.rs:835
  15: miniscript::policy::compiler::best_t
             at DIR/.cargo/git/checkouts/rust-miniscript-1175aea50517de2b/8ad6fea/src/policy/compiler.rs:1102
  16: miniscript::policy::compiler::best_compilation
             at DIR/.cargo/git/checkouts/rust-miniscript-1175aea50517de2b/8ad6fea/src/policy/compiler.rs:1079
  17: miniscript::policy::concrete::Policy<Pk>::compile
             at DIR/.cargo/git/checkouts/rust-miniscript-1175aea50517de2b/8ad6fea/src/policy/concrete.rs:67
  18: […]::main
             at src/main.rs:12
…
```

**Comment by practicalswift** [comment]
Oh, sorry! Wrong repo!
