### ISSUE TITLE
(New) fuzz failure in bitcoin_deserialize_psbt

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#3628]
With fuzz input

```
70736274ff01000a000000ff0000000074ff4f010488b21eff02000001004a92244992244902030203030303030303030303030303030303030303030303030303030303030303f4000000000000000a000208ffffffff08080804000000000000000c080808000b000000000001000070736274ff01000a000000ff0000000074ff4f010488b21eff02000001004a92244992244902030203030303030303030303030303030303030303030303030303030303030303f4000000000000000a000208ffffffff08080804000000000000000800000000000000100000014000000000000000000a010000000000000000000874ff010008000000000000000a0000000000000000000008020a00000000000000000200000000000000000000000fffffffffffffff3bb1133bb1133b01000002080808080808b7954f95ee00644986fd0b00fe01000000fefefefefefefefefefefefefefea798fe00000000000000000000000000000000400000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002d35383734300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024924924924924a0000000249240000010000000100000000000000000002027562020000ff0100000001000000c32d00000000000082f97462010001000100000000000900000a0000010000000011000000000000fc0000000000c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c674ff01000a010000000000000000000874ff010008000000000000000a0000000000000000000008020a000000010000000000000000020000000000000000000800000000000fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00ff0000ffffffffffff0065cd1dffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2ac6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c63437393635e8553639316e3a0038383838383838383838383838383838383851696fd5450000000100000000ffcf0200
```

I see a crash

```

---- tests::duplicate_crash stdout ----
thread 'tests::duplicate_crash' panicked at bitcoin/src/psbt/mod.rs:259:40:
attempt to subtract with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:145:5
   3: bitcoin::psbt::Psbt::combine
             at /store/home/apoelstra/code/rust-bitcoin/rust-bitcoin/master/bitcoin/src/psbt/mod.rs:259:40
   4: bitcoin_deserialize_psbt::do_test
             at ./fuzz_targets/bitcoin/deserialize_psbt.rs:33:70
   5: bitcoin_deserialize_psbt::tests::duplicate_crash
             at ./fuzz_targets/bitcoin/deserialize_psbt.rs:71:9
   6: bitcoin_deserialize_psbt::tests::duplicate_crash::{{closure}}
             at ./fuzz_targets/bitcoin/deserialize_psbt.rs:68:25
   7: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This looks like a pretty old codepath so may be something we need to backport.

**Comment by apoelstra** [comment]
The offending commit is 7f5c2795d6d581276119edf2becf4377d7c7df08 in #499.
